language: scala
jdk:
   - openjdk7
   - openjdk6
scala:
   - 2.10.3
   - 2.11.0-RC3
sbt_args: "'set resolvers += \"Sonatype OSS Snapshots\" at \"https://oss.sonatype.org/content/repositories/snapshots\"'"

branches:
  only:
    - master
    - "2.3"
