language: scala
scala:
   - 2.9.1
   - 2.9.2
   - 2.10.0
   - 2.10.1
   - 2.10.2
jdk:
   - oraclejdk7
   - openjdk7
   - openjdk6
script: sbt 'set resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"' ++$TRAVIS_SCALA_VERSION test
