language: scala
jdk:
   - openjdk7
   - openjdk6
scala:
   - 2.10.3
   - 2.11.0-RC3
sbt_args: "'set resolvers += \"Sonatype OSS Snapshots\" at \"https://oss.sonatype.org/content/repositories/snapshots\"'"

after_success:
  - echo ${TRAVIS_PULL_REQUEST}
  - echo ${TRAVIS_JDK_VERSION}
  - >
      test "${TRAVIS_PULL_REQUEST}" = 'false' &&
      test "${TRAVIS_JDK_VERSION}" = 'openjdk6' &&
      sbt 'set resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"'
      "set credentials += Credentials(\"Sonatype Nexus Repository Manager\", \"oss.sonatype.org\", \"${SONATYPE_USER}\", \"${SONATYPE_PASS}\")"
      publish

branches:
  only:
    - master
    - "2.3"

env:
  global:
    - secure: "QpExOUiP4ftCERMXVJb/Rj5lDYbhKqQQOaY6JqNsF+SqKJs1aoWkZeDpTX3gBkV1UlUMDIiIzCYaAoR6YN+EQ0xd43KLw2HEJ0yaa4CIc9RUeB5+iuF9TJh2xoQ1vkwVDwdb64b7nqC1slEPazO5qOcZaA0UgK1Dj9gcoj0FTyM="
    - secure: "U7yTgSNOUldyJ1DpEMBMRjDjd0XXsFQon7UAhJSPo+/L+1woz11DuX7OMd6JE5sdp/da2uiTzNlqblzh+75ekve04c9S9fEfEjQ5VWWNRFFFWwCMVKkWdXzi8oT8/2H8+MYXuwgh8k7LDahIs3pvaOI/2e11Jrfo5jTqOdubHOY="